const guides = [
  {id:'forbidden-city',wiki:'Forbidden_City',name:'故宫博物院',place:'北京 · 东城区',type:'人文历史',season:'3—5 月 / 9—10 月',days:'半日—1 日',color:'#b96f56',land:'#633d32',intro:'在六百年宫墙的阴影里，读一座城的时间。',best:'开门后 30 分钟',budget:'门票 60 元起',arrival:'地铁 1 号线天安门东站，步行约 10 分钟。',stay:'东四、灯市口一带，步行与地铁衔接方便。',tip:'需实名提前预约；周一闭馆。午后游客密度较低。',plan:[['上午','午门入场，依次走外朝三大殿，建议先看太和殿广场的中轴线。'],['下午','由乾清宫进入内廷，沿东六宫或西六宫择一深入，再由神武门离开。'],['傍晚','从景山公园南门上山，在万春亭看故宫全景与日落。']]},
  {id:'great-wall',wiki:'Badaling',name:'八达岭长城',place:'北京 · 延庆区',type:'人文历史',season:'4—5 月 / 9—11 月',days:'1 日',color:'#819275',land:'#3a563c',intro:'把脚步交给城砖，向北方的群山慢慢走。',best:'08:00 前',budget:'门票 40 元起',arrival:'北京北站乘市郊铁路 S2，或德胜门乘旅游专线。',stay:'建议住市区，当日往返；体力有限可选择缆车。',tip:'北八楼坡度较大，穿防滑鞋；避开节假日正午。',plan:[['上午','从北七楼至北八楼登高，先完成体力要求最高的一段。'],['下午','回到北四楼后可继续向北一、二楼缓行，留足下山时间。'],['傍晚','返回北京城区，在什刹海或鼓楼一带安排晚餐。']]},
  {id:'jiuzhaigou',wiki:'Jiuzhaigou',name:'九寨沟',place:'四川 · 阿坝州',type:'自然风光',season:'9—10 月',days:'2 日',color:'#55939a',land:'#17575d',intro:'山谷里的水，把蓝色分成了无数种层次。',best:'沟口开园时',budget:'门票与观光车约 280 元',arrival:'九寨黄龙机场或成都经高速抵达；旺季优先选飞机或包车。',stay:'沟口步行范围内，次日进入景区最省时。',tip:'海拔约 2000 米，早晚温差大；全程使用环保观光车。',plan:[['上午','第一天乘车至长海、五彩池，顺势下行至诺日朗瀑布。'],['下午','沿日则沟游览五花海、珍珠滩，预留时间慢走栈道。'],['第二日','前往则查洼沟与树正沟，镜海建议在无风的早晨抵达。']]},
  {id:'zhangjiajie',wiki:'Zhangjiajie_National_Forest_Park',name:'张家界国家森林公园',place:'湖南 · 张家界',type:'自然风光',season:'4—6 月 / 9—11 月',days:'3 日',color:'#667c64',land:'#2a4937',intro:'石峰从云海里生长出来，像一场缓慢的奇观。',best:'08:00 前',budget:'门票 225 元起',arrival:'张家界西站或荷花机场抵达，住武陵源标志门附近。',stay:'武陵源东门附近，往返景区与餐饮都方便。',tip:'山上山下温差明显；电梯与索道高峰期需要排队。',plan:[['第一日','东门入园，走金鞭溪至水绕四门，乘百龙天梯上袁家界。'],['第二日','天子山、贺龙公园、十里画廊串联，下午下山休息。'],['第三日','杨家界天波府或黄石寨二选一，保留一段徒步时间。']]},
  {id:'huangshan',wiki:'Huangshan',name:'黄山',place:'安徽 · 黄山市',type:'自然风光',season:'4—5 月 / 9—11 月',days:'2 日',color:'#9a8f70',land:'#514b37',intro:'云海、奇松和花岗岩，让一夜山居变得很值得。',best:'日出前 40 分钟',budget:'门票 190 元起',arrival:'黄山北站转景区巴士至汤口，再换乘新国线。',stay:'山上酒店需提前预订；轻装上山最舒适。',tip:'天气决定景观，出发前看云海预报；石阶湿滑需防滑鞋。',plan:[['第一日','云谷寺索道上山，游始信峰、黑虎松、北海至排云亭。'],['傍晚','西海排云亭看晚霞，住光明顶或白云宾馆周边。'],['第二日','光明顶日出后，经鳌鱼峰、百步云梯至迎客松，下山泡温泉。']]},
  {id:'west-lake',wiki:'West_Lake',name:'杭州西湖',place:'浙江 · 杭州市',type:'城市漫游',season:'3—5 月 / 10—11 月',days:'1—2 日',color:'#879e9d',land:'#435e5e',intro:'不必赶路，沿湖走一圈就能理解江南的留白。',best:'清晨或日落前',budget:'大部分湖岸免费',arrival:'地铁 1 号线龙翔桥站，步行约 15 分钟至湖滨。',stay:'湖滨、吴山或凤起路，夜间散步与公共交通更便利。',tip:'节假日建议逆时针走湖岸；租船前确认天气与末班时间。',plan:[['清晨','从断桥出发，经白堤走到平湖秋月，避开旅行团高峰。'],['下午','孤山、曲院风荷与苏堤分段漫游，累时可搭观光车。'],['傍晚','雷峰塔一带看落日，夜晚回湖滨看音乐喷泉。']]},
  {id:'potala',wiki:'Potala_Palace',name:'布达拉宫',place:'西藏 · 拉萨市',type:'高原徒步',season:'5—6 月 / 9—10 月',days:'1—2 日',color:'#a76b5d',land:'#633b35',intro:'在高原的阳光下，拾级走进雪域文明的中心。',best:'预约时段前 30 分钟',budget:'门票 200 元起',arrival:'拉萨贡嘎机场乘机场巴士进城；先在市区适应海拔。',stay:'八廓街或布达拉宫周边，第一晚不要安排剧烈活动。',tip:'必须提前预约；参观时长有限，严禁航拍与部分区域拍照。',plan:[['第一日','抵达拉萨后低强度适应，逛八廓街并补充水分与碳水。'],['第二日','按预约时间参观布达拉宫，下午在药王山观景台拍摄全景。'],['傍晚','慢步至宗角禄康公园，以放松为主，避免饮酒和跑跳。']]},
  {id:'li-river',wiki:'Li_River',name:'漓江',place:'广西 · 桂林—阳朔',type:'自然风光',season:'4—5 月 / 9—10 月',days:'2 日',color:'#759d81',land:'#355b42',intro:'一条江把喀斯特峰林，展开成一幅会呼吸的画。',best:'07:00 前',budget:'游船约 250 元起',arrival:'桂林两江机场或桂林站抵达，建议桂林进、阳朔出。',stay:'阳朔西街外围或十里画廊，夜晚相对安静。',tip:'丰水期景色浓郁，雨天备好防水袋；选正规码头与游船。',plan:[['第一日','桂林磨盘山码头登船，沿江观九马画山、黄布倒影至阳朔。'],['下午','兴坪古镇散步，登老寨山或相公山看峰林层次。'],['第二日','骑行十里画廊，遇龙河竹筏安排在上午水面更平静时。']]},
  {id:'terracotta',wiki:'Terracotta_Army',name:'秦始皇兵马俑',place:'陕西 · 西安市',type:'人文历史',season:'3—5 月 / 9—11 月',days:'半日—1 日',color:'#a57d61',land:'#624838',intro:'两千年前的军阵，仍在黄土之下保持着沉默的秩序。',best:'开馆即入',budget:'门票 120 元起',arrival:'西安站或钟楼附近乘景区专线；打车约 50 分钟。',stay:'住西安市区，参观后返回城墙或回民街继续游览。',tip:'一号坑人流最大，先看二号、三号坑再进入一号坑体验更好。',plan:[['上午','从二号坑开始，了解跪射俑与军阵构成，再走三号坑。'],['中午','景区简餐后前往一号坑，观看修复区与军阵全景。'],['下午','参观铜车马陈列馆，返回西安市区看大雁塔夜景。']]},
  {id:'yading',wiki:'Yading_Nature_Reserve',name:'稻城亚丁',place:'四川 · 甘孜州',type:'高原徒步',season:'9—10 月',days:'3—4 日',color:'#6789a0',land:'#2e5269',intro:'雪山、草甸和海子，是身体抵达高处之后的奖赏。',best:'首班观光车',budget:'门票与观光车约 270 元',arrival:'稻城亚丁机场或康定包车；先在香格里拉镇住一晚适应。',stay:'香格里拉镇海拔相对友好，餐饮与补给更齐全。',tip:'全程高海拔，量力而行；牛奶海徒步往返约 5—6 小时。',plan:[['第一日','抵达香格里拉镇适应海拔，检查雨具、防晒与保温层。'],['第二日','长线：扎灌崩—洛绒牛场—牛奶海—五色海，尽早出发。'],['第三日','短线：冲古寺—珍珠海，下午返镇休息或离开。']]}
];

const grid = document.querySelector('#guide-grid');
const search = document.querySelector('#search');
const dialog = document.querySelector('#guide-dialog');
const dialogContent = document.querySelector('#dialog-content');
const emptyState = document.querySelector('#empty-state');
let activeFilter = '全部';
let saved = new Set(JSON.parse(localStorage.getItem('mountain-notes-saved') || '[]'));

function renderSkeletons() { grid.innerHTML = ''; for (let i = 0; i < 6; i += 1) grid.append(document.querySelector('#skeleton-template').content.cloneNode(true)); }
function filteredGuides() { const term = search.value.trim().toLowerCase(); return guides.filter(g => (activeFilter === '全部' || g.type === activeFilter) && `${g.name} ${g.place} ${g.type} ${g.intro}`.toLowerCase().includes(term)); }
function renderGuides() { const results = filteredGuides(); grid.innerHTML = ''; emptyState.hidden = results.length > 0; results.forEach((guide, index) => { const card = document.createElement('button'); const hasPhoto = Boolean(guide.image); card.type='button'; card.className='guide-card'; card.style.setProperty('--i', index); card.innerHTML = `<div class="card-art ${hasPhoto ? 'has-photo' : ''}" style="--card:${guide.color};--land:${guide.land}" aria-hidden="true">${hasPhoto ? `<img class="card-photo" src="${guide.image}" alt="" loading="lazy" />` : ''}</div><div class="card-label"><span>${guide.type}</span><span>${guide.days}</span></div><h3>${guide.name}</h3><p>${guide.place}</p>`; card.addEventListener('click', () => openGuide(guide)); grid.append(card); }); }
function openGuide(guide) { const isSaved = saved.has(guide.id); const heroPhoto = guide.image ? `<img class="detail-photo" src="${guide.image}" alt="${guide.name}景观" />` : ''; dialogContent.innerHTML = `<section class="detail-hero" style="--detail:${guide.color}">${heroPhoto}<p class="eyebrow">${guide.type.toUpperCase()} · ${guide.place}</p><h2 id="dialog-title">${guide.name}</h2><p>${guide.intro}</p></section><div class="detail-body"><div><h3>推荐行程</h3>${guide.plan.map((item, i) => `<article class="day"><strong>${i === 0 ? 'DAY 01' : `DAY 0${i + 1}`}</strong><div><h4>${item[0]}</h4><p>${item[1]}</p></div></article>`).join('')}</div><aside><h3>出发前，先知道这些</h3><dl class="info-list"><div><dt>推荐季节</dt><dd>${guide.season}</dd></div><div><dt>最佳抵达</dt><dd>${guide.best}</dd></div><div><dt>参考花费</dt><dd>${guide.budget}</dd></div><div><dt>怎么抵达</dt><dd>${guide.arrival}</dd></div><div><dt>住在哪里</dt><dd>${guide.stay}</dd></div><div><dt>手册提醒</dt><dd>${guide.tip}</dd></div></dl><button class="save-button ${isSaved ? 'saved' : ''}" data-save="${guide.id}">${isSaved ? '已收进我的行程' : '收藏这篇攻略'}</button></aside></div>`; dialog.showModal(); document.querySelector('[data-save]').addEventListener('click', event => toggleSaved(event.currentTarget, guide.id)); }
function toggleSaved(button, id) { if (saved.has(id)) saved.delete(id); else saved.add(id); localStorage.setItem('mountain-notes-saved', JSON.stringify([...saved])); button.classList.toggle('saved'); button.textContent = saved.has(id) ? '已收进我的行程' : '收藏这篇攻略'; }
document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item === button)); renderGuides(); }));
document.querySelectorAll('[data-filter]').forEach(button => { if (!button.classList.contains('filter')) button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item.dataset.filter === activeFilter)); document.querySelector('#guides').scrollIntoView({behavior:'smooth'}); renderGuides(); }); });
search.addEventListener('input', renderGuides); document.querySelector('#clear-filters').addEventListener('click', () => { activeFilter = '全部'; search.value = ''; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item.dataset.filter === '全部')); renderGuides(); }); document.querySelectorAll('[data-scroll]').forEach(button => button.addEventListener('click', () => document.getElementById(button.dataset.scroll).scrollIntoView({behavior:'smooth'}))); document.querySelector('.close-dialog').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); });
async function loadGuidePhotos() {
  await Promise.all(guides.map(async guide => {
    try {
      const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${guide.wiki}`);
      const data = await response.json();
      guide.image = data.thumbnail?.source || data.originalimage?.source;
    } catch { /* The illustrated fallback remains available offline. */ }
  }));
  renderGuides();
}

renderSkeletons(); setTimeout(renderGuides, 320); loadGuidePhotos();
